-- PARTE 3: 115 productos
DELETE FROM products;
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-201', 'Suavinex ASPIRADOR NASAL', 'Suavinex ASPIRADOR NASAL', 6.15, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20ASPIRADOR%20NASAL', NULL, 6, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-202', 'Suavinex TIJERITA INFANTIL DREAMS', 'Suavinex TIJERITA INFANTIL DREAMS', 6.75, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20TIJERITA%20INFANTI', NULL, 7, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-203', 'Suavinex ESPONJA HIDROFILA', 'Suavinex ESPONJA HIDROFILA', 4.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20ESPONJA%20HIDROFIL', NULL, 5, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-204', 'Suavinex ESPONJA CANASTILLA NATURAL', 'Suavinex ESPONJA CANASTILLA NATURAL', 10.45, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20ESPONJA%20CANASTIL', NULL, 10, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-205', 'Suavinex ESPONJA BAMBOO', 'Suavinex ESPONJA BAMBOO', 7.45, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20ESPONJA%20BAMBOO', NULL, 7, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-206', 'Suavinex ESPONJA CON IONES DE PLATA', 'Suavinex ESPONJA CON IONES DE PLATA', 7.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20ESPONJA%20CON%20IONE', NULL, 8, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-207', 'Suavinex ESPONJA BABY AROMA LECHE', 'Suavinex ESPONJA BABY AROMA LECHE', 9.25, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20ESPONJA%20BABY%20ARO', NULL, 9, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-208', 'Suavinex ESPONJA NATURAL GRANDE', 'Suavinex ESPONJA NATURAL GRANDE', 6.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20ESPONJA%20NATURAL%20', NULL, 7, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-209', 'Suavinex ESPONJA INGLESA', 'Suavinex ESPONJA INGLESA', 8.75, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20ESPONJA%20INGLESA', NULL, 9, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-210', 'Suavinex MORDEDOR MUSICAL FLOR +OM', 'Suavinex MORDEDOR MUSICAL FLOR +OM', 9.25, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20MORDEDOR%20MUSICAL', NULL, 9, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-211', 'Suavinex MORDEDOR ETAPA 1 +0M', 'Suavinex MORDEDOR ETAPA 1 +0M', 5.45, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20MORDEDOR%20ETAPA%201', NULL, 5, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-212', 'Suavinex MORDEDOR REFRIGERANTE ETAPA 2 +4M', 'Suavinex MORDEDOR REFRIGERANTE ETAPA 2 +4M', 5.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20MORDEDOR%20REFRIGE', NULL, 6, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-213', 'Suavinex MORDEDOR DIDÁCTICO ETAPA 3 +6M', 'Suavinex MORDEDOR DIDÁCTICO ETAPA 3 +6M', 8.25, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20MORDEDOR%20DID%C3%81CTI', NULL, 8, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-214', 'Suavinex SEL MORDEDOR CONEJO S +0M WONDERLAND', 'Suavinex SEL MORDEDOR CONEJO S +0M WONDERLAND', 7.75, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20SEL%20MORDEDOR%20CON', NULL, 8, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-215', 'Suavinex SEL MORDEDOR SIL +0M COLOUR ESSENCE', 'Suavinex SEL MORDEDOR SIL +0M COLOUR ESSENCE', 9.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20SEL%20MORDEDOR%20SIL', NULL, 10, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-216', 'Suavinex SEL MORDEDOR SIL REFR +4M COLOUR ESSEN', 'Suavinex SEL MORDEDOR SIL REFR +4M COLOUR ESSEN', 10.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20SEL%20MORDEDOR%20SIL', NULL, 11, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-217', 'Suavinex SEL MORDEDOR DIDÁC SIL +6M COLOUR ESS', 'Suavinex SEL MORDEDOR DIDÁC SIL +6M COLOUR ESS', 11.5, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20SEL%20MORDEDOR%20DID', NULL, 12, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-218', 'Suavinex SONAJERO GALAXY 3 BOLAS', 'Suavinex SONAJERO GALAXY 3 BOLAS', 6.85, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20SONAJERO%20GALAXY%20', NULL, 7, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-219', 'Suavinex DISCOS LACTANCIA NATURE 60 U', 'Suavinex DISCOS LACTANCIA NATURE 60 U', 11.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20DISCOS%20LACTANCIA', NULL, 12, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-220', 'Suavinex OFERTA DISCOS LACTANCIA NATURE 60+30 U', 'Suavinex OFERTA DISCOS LACTANCIA NATURE 60+30 U', 9.5, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20OFERTA%20DISCOS%20LA', NULL, 10, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-221', 'Suavinex BABY TOALLITAS DERMOHIDRATANTES 25U', 'Suavinex BABY TOALLITAS DERMOHIDRATANTES 25U', 1.99, NULL, 'higiene', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20BABY%20TOALLITAS%20D', NULL, 2, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-222', 'Suavinex BABY TOALLITAS AQUA CARE 60U', 'Suavinex BABY TOALLITAS AQUA CARE 60U', 3.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20BABY%20TOALLITAS%20A', NULL, 4, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-223', 'Suavinex BABY TOALL AQUA CARE 60U PACK 3', 'Suavinex BABY TOALL AQUA CARE 60U PACK 3', 10.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20BABY%20TOALL%20AQUA%20', NULL, 11, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-224', 'Suavinex BABY TOALL DERMOHIDRATANTES 60U PACK 3', 'Suavinex BABY TOALL DERMOHIDRATANTES 60U PACK 3', 8.75, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20BABY%20TOALL%20DERMO', NULL, 9, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-225', 'Suavinex BABY TOALLITAS DERMOHIDRATANTES 60U', 'Suavinex BABY TOALLITAS DERMOHIDRATANTES 60U', 3.75, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20BABY%20TOALLITAS%20D', NULL, 4, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-226', 'Suavinex ZERO SET BIB 180ML A +CH -2-2M FAIR', 'Suavinex ZERO SET BIB 180ML A +CH -2-2M FAIR', 17.25, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20ZERO%20SET%20BIB%20180', NULL, 17, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-227', 'Suavinex ZERO SET BIB 180ML A +CH -2-2M LIGHT', 'Suavinex ZERO SET BIB 180ML A +CH -2-2M LIGHT', 17.25, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20ZERO%20SET%20BIB%20180', NULL, 17, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-228', 'Suavinex ZERO SET BIB 180ML A +CH -2-2M MEDIUM', 'Suavinex ZERO SET BIB 180ML A +CH -2-2M MEDIUM', 17.25, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20ZERO%20SET%20BIB%20180', NULL, 17, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-229', 'Suavinex ZERO SET BIB 180ML A +CH -2-2M DEEP', 'Suavinex ZERO SET BIB 180ML A +CH -2-2M DEEP', 17.25, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20ZERO%20SET%20BIB%20180', NULL, 17, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-230', 'Suavinex WELCOME BABY CARE SET DREAMS BLUE', 'Suavinex WELCOME BABY CARE SET DREAMS BLUE', 50.95, NULL, 'cosmetica-belleza', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20WELCOME%20BABY%20CAR', NULL, 51, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-231', 'Suavinex WELCOME BABY CARE SET DREAMS PINK', 'Suavinex WELCOME BABY CARE SET DREAMS PINK', 50.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20WELCOME%20BABY%20CAR', NULL, 51, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-232', 'Suavinex ESSENTIALS BABY CARE SET DREAMS BLUE', 'Suavinex ESSENTIALS BABY CARE SET DREAMS BLUE', 21.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20ESSENTIALS%20BABY%20', NULL, 22, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-233', 'Suavinex ESSENTIALS BABY CARE SET DREAMS PINK', 'Suavinex ESSENTIALS BABY CARE SET DREAMS PINK', 21.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20ESSENTIALS%20BABY%20', NULL, 22, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-234', 'Suavinex WELCOME BABY CARE SET DREAMS BEIGE', 'Suavinex WELCOME BABY CARE SET DREAMS BEIGE', 50.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20WELCOME%20BABY%20CAR', NULL, 51, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-235', 'Suavinex ESSENTIALS BABY CARE SET DREAMS BEIGE', 'Suavinex ESSENTIALS BABY CARE SET DREAMS BEIGE', 21.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20ESSENTIALS%20BABY%20', NULL, 22, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-236', 'Suavinex BABY MY LITTLE BACKPACK LEON', 'Suavinex BABY MY LITTLE BACKPACK LEON', 46.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20BABY%20MY%20LITTLE%20B', NULL, 47, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-237', 'Suavinex BABY MY LITTLE BACKPACK ELEFANTE', 'Suavinex BABY MY LITTLE BACKPACK ELEFANTE', 46.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20BABY%20MY%20LITTLE%20B', NULL, 47, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-238', 'Suavinex BABY CARE WIPES POUCH 25 DREAMS BLUE', 'Suavinex BABY CARE WIPES POUCH 25 DREAMS BLUE', 27.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20BABY%20CARE%20WIPES%20', NULL, 28, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-239', 'Suavinex BABY CARE WIPES POUCH 25 DREAMS PINK', 'Suavinex BABY CARE WIPES POUCH 25 DREAMS PINK', 27.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20BABY%20CARE%20WIPES%20', NULL, 28, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-240', 'Suavinex BABY CARE ORGANISER 25 DREAMS2 BLUE', 'Suavinex BABY CARE ORGANISER 25 DREAMS2 BLUE', 40.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20BABY%20CARE%20ORGANI', NULL, 41, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-241', 'Suavinex BABY CARE ORGANISER 25 DREAMS2 PINK', 'Suavinex BABY CARE ORGANISER 25 DREAMS2 PINK', 40.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20BABY%20CARE%20ORGANI', NULL, 41, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-242', 'Suavinex SET BABY COLOGNE 100+50ML + PELUCHE', 'Suavinex SET BABY COLOGNE 100+50ML + PELUCHE', 29.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20SET%20BABY%20COLOGNE', NULL, 30, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-243', 'Suavinex COFRE DEAR MOMMY + BABY COLOGNE 100ML', 'Suavinex COFRE DEAR MOMMY + BABY COLOGNE 100ML', 37, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20COFRE%20DEAR%20MOMMY', NULL, 37, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-244', 'Suavinex SET BC MEMORIES 100+50ML + PELUCHE', 'Suavinex SET BC MEMORIES 100+50ML + PELUCHE', 29.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20SET%20BC%20MEMORIES%20', NULL, 30, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-245', 'Suavinex BABY GEL-CREMA BAÑO SUAVE 750ML', 'Suavinex BABY GEL-CREMA BAÑO SUAVE 750ML', 16.95, NULL, 'cosmetica-belleza', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20BABY%20GEL-CREMA%20B', NULL, 17, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-246', 'Suavinex BABY LECHE HIDRATANTE CORPORAL 750ML', 'Suavinex BABY LECHE HIDRATANTE CORPORAL 750ML', 18.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20BABY%20LECHE%20HIDRA', NULL, 19, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-247', 'Suavinex BABY GEL BAÑO ESPUMOSO 500ML', 'Suavinex BABY GEL BAÑO ESPUMOSO 500ML', 11.5, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20BABY%20GEL%20BA%C3%91O%20ES', NULL, 12, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-248', 'Suavinex BABY GEL BAÑO ESPUMOSO 750ML', 'Suavinex BABY GEL BAÑO ESPUMOSO 750ML', 13.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20BABY%20GEL%20BA%C3%91O%20ES', NULL, 14, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-249', 'Suavinex BABY I LOVE BATH TIME LECHE+GEL 500ML', 'Suavinex BABY I LOVE BATH TIME LECHE+GEL 500ML', 22.75, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20BABY%20I%20LOVE%20BATH', NULL, 23, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-250', 'Suavinex BABY MI PRIMERA CREMA FACIAL 50ML', 'Suavinex BABY MI PRIMERA CREMA FACIAL 50ML', 9.75, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20BABY%20MI%20PRIMERA%20', NULL, 10, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-251', 'Suavinex BABY MI PRIMERA CREMA FAC SPF30 50ML', 'Suavinex BABY MI PRIMERA CREMA FAC SPF30 50ML', 12.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20BABY%20MI%20PRIMERA%20', NULL, 13, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-252', 'Suavinex BABY POMADA PROTECTORA REPARADORA 75ML', 'Suavinex BABY POMADA PROTECTORA REPARADORA 75ML', 12.35, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20BABY%20POMADA%20PROT', NULL, 12, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-253', 'Suavinex BABY ACEITE DE MASAJE HIDRATANTE 100ML', 'Suavinex BABY ACEITE DE MASAJE HIDRATANTE 100ML', 12.25, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20BABY%20ACEITE%20DE%20M', NULL, 12, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-254', 'Suavinex BABY BALSAMO PECTORAL AROMATICO 50ML', 'Suavinex BABY BALSAMO PECTORAL AROMATICO 50ML', 9, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20BABY%20BALSAMO%20PEC', NULL, 9, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-255', 'Suavinex BABY CHAMPU EXTRA SUAVE 500ML', 'Suavinex BABY CHAMPU EXTRA SUAVE 500ML', 11.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20BABY%20CHAMPU%20EXTR', NULL, 12, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-256', 'Suavinex BABY CREMA DE PAÑAL 75ML', 'Suavinex BABY CREMA DE PAÑAL 75ML', 8.75, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20BABY%20CREMA%20DE%20PA', NULL, 9, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-257', 'Suavinex BABY GEL-CREMA BAÑO SUAVE 500ML', 'Suavinex BABY GEL-CREMA BAÑO SUAVE 500ML', 13.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20BABY%20GEL-CREMA%20B', NULL, 14, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-258', 'Suavinex BABY LECHE HIDRATANTE CORPORAL 500ML', 'Suavinex BABY LECHE HIDRATANTE CORPORAL 500ML', 15.5, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20BABY%20LECHE%20HIDRA', NULL, 16, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-259', 'Suavinex KIDS GEL CHAMPU 200ML', 'Suavinex KIDS GEL CHAMPU 200ML', 7.25, NULL, 'cosmetica-belleza', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20KIDS%20GEL%20CHAMPU%20', NULL, 7, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-260', 'Suavinex KIDS CHAMPU ACONDICIONADOR 300ML', 'Suavinex KIDS CHAMPU ACONDICIONADOR 300ML', 8.75, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20KIDS%20CHAMPU%20ACON', NULL, 9, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-261', 'Suavinex KIDS SPRAY DESENREDANTE 250ML', 'Suavinex KIDS SPRAY DESENREDANTE 250ML', 9.25, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20KIDS%20SPRAY%20DESEN', NULL, 9, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-262', 'Suavinex KIDS FUN AND SILKY SET CEPILLO+SPRAY', 'Suavinex KIDS FUN AND SILKY SET CEPILLO+SPRAY', 15.45, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20KIDS%20FUN%20AND%20SIL', NULL, 15, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-263', 'Suavinex KIDS DEO ROLL-ON 50ML', 'Suavinex KIDS DEO ROLL-ON 50ML', 7.25, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20KIDS%20DEO%20ROLL-ON', NULL, 7, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-264', 'Suavinex KIDS DEO ROLL-ON 12UN CAJA EXPOSITORA', 'Suavinex KIDS DEO ROLL-ON 12UN CAJA EXPOSITORA', 7.25, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20KIDS%20DEO%20ROLL-ON', NULL, 7, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-265', 'Suavinex PIOJO LENDRERA', 'Suavinex PIOJO LENDRERA', 10.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20PIOJO%20LENDRERA', NULL, 11, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-266', 'Suavinex PIOJO CHAMPU PROTECT ARBOL DE TE 250ML', 'Suavinex PIOJO CHAMPU PROTECT ARBOL DE TE 250ML', 8.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20PIOJO%20CHAMPU%20PRO', NULL, 9, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-267', 'Suavinex PIOJO SPRAY PROTECT ARBOL DE TE 250ML', 'Suavinex PIOJO SPRAY PROTECT ARBOL DE TE 250ML', 10.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20PIOJO%20SPRAY%20PROT', NULL, 11, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-268', 'Suavinex PIOJO LOCION ANTIPIOJOS 125ML+LENDRERA', 'Suavinex PIOJO LOCION ANTIPIOJOS 125ML+LENDRERA', 20.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20PIOJO%20LOCION%20ANT', NULL, 21, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-269', 'Suavinex PIOJO SET LOCION 125ML+CHAMPU 250ML', 'Suavinex PIOJO SET LOCION 125ML+CHAMPU 250ML', 26.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20PIOJO%20SET%20LOCION', NULL, 27, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-270', 'Suavinex MOM ACEITE MASAJE PERINEAL 30ML', 'Suavinex MOM ACEITE MASAJE PERINEAL 30ML', 12.5, NULL, 'cosmetica-belleza', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20MOM%20ACEITE%20MASAJ', NULL, 13, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-271', 'Suavinex MOM CUID ESENCIAL ESTRIAS ACEITE 100ML', 'Suavinex MOM CUID ESENCIAL ESTRIAS ACEITE 100ML', 23.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20MOM%20CUID%20ESENCIA', NULL, 24, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-272', 'Suavinex MOM CUID ESENCIAL ESTRÍAS CREMA 400ML', 'Suavinex MOM CUID ESENCIAL ESTRÍAS CREMA 400ML', 34.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20MOM%20CUID%20ESENCIA', NULL, 35, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-273', 'Suavinex MOM BALSAMO PEZON 30ML', 'Suavinex MOM BALSAMO PEZON 30ML', 10.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20MOM%20BALSAMO%20PEZO', NULL, 11, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-274', 'Suavinex SPRAY NASAL NARIZ TAP HIPER +3M 120ML', 'Suavinex SPRAY NASAL NARIZ TAP HIPER +3M 120ML', 10.9, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20SPRAY%20NASAL%20NARI', NULL, 11, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-275', 'Suavinex SPRAY NASAL ISO ALOE FME +3A 120ML', 'Suavinex SPRAY NASAL ISO ALOE FME +3A 120ML', 10.9, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20SPRAY%20NASAL%20ISO%20', NULL, 11, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-276', 'Suavinex SPRAY NASAL PEDIATR ISO ALOE +0M 120ML', 'Suavinex SPRAY NASAL PEDIATR ISO ALOE +0M 120ML', 10.9, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20SPRAY%20NASAL%20PEDI', NULL, 11, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-277', 'Suavinex ASPIRADOR NASAL', 'Suavinex ASPIRADOR NASAL', 11.9, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20ASPIRADOR%20NASAL', NULL, 12, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-278', 'Suavinex RECAMBIOS ASPIRADOR NASAL 12UN', 'Suavinex RECAMBIOS ASPIRADOR NASAL 12UN', 6.9, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20RECAMBIOS%20ASPIRA', NULL, 7, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-279', 'Suavinex LIMPIADOR NASAL', 'Suavinex LIMPIADOR NASAL', 5.99, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20LIMPIADOR%20NASAL', NULL, 6, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-280', 'Suavinex BABY COLOGNE 100ML', 'Suavinex BABY COLOGNE 100ML', 16.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20BABY%20COLOGNE%20100', NULL, 17, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-281', 'Suavinex BABY COLOGNE MEMORIES 100ML', 'Suavinex BABY COLOGNE MEMORIES 100ML', 16.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20BABY%20COLOGNE%20MEM', NULL, 17, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-282', 'Suavinex BABY COLOGNE SENSE 100ML', 'Suavinex BABY COLOGNE SENSE 100ML', 16.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20BABY%20COLOGNE%20SEN', NULL, 17, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-283', 'Suavinex KIDS AGUA DE COLONIA 100ML', 'Suavinex KIDS AGUA DE COLONIA 100ML', 16.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20KIDS%20AGUA%20DE%20COL', NULL, 17, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-284', 'Suavinex DEAR MOMMY COLONIA 100ML', 'Suavinex DEAR MOMMY COLONIA 100ML', 24.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20DEAR%20MOMMY%20COLON', NULL, 25, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-285', 'Suavinex SEL NECESER WONDERLAND BG', 'Suavinex SEL NECESER WONDERLAND BG', 24.9, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20SEL%20NECESER%20WOND', NULL, 25, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-286', 'Suavinex SEL NECESER WONDERLAND LIB', 'Suavinex SEL NECESER WONDERLAND LIB', 24.9, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20SEL%20NECESER%20WOND', NULL, 25, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-287', 'Suavinex SEL NECESER WONDERLAND GR', 'Suavinex SEL NECESER WONDERLAND GR', 24.9, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20SEL%20NECESER%20WOND', NULL, 25, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-288', 'Suavinex SEL NECESER WONDERLAND RS', 'Suavinex SEL NECESER WONDERLAND RS', 24.9, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20SEL%20NECESER%20WOND', NULL, 25, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-289', 'Suavinex SEL PORTADOCOCUMENTOS WONDERLAND BG', 'Suavinex SEL PORTADOCOCUMENTOS WONDERLAND BG', 27.9, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20SEL%20PORTADOCOCUM', NULL, 28, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-290', 'Suavinex SEL PORTADOCOCUMENTOS WONDERLAND LIB', 'Suavinex SEL PORTADOCOCUMENTOS WONDERLAND LIB', 27.9, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20SEL%20PORTADOCOCUM', NULL, 28, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-291', 'Suavinex SEL PORTADOCOCUMENTOS WONDERLAND GR', 'Suavinex SEL PORTADOCOCUMENTOS WONDERLAND GR', 27.9, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20SEL%20PORTADOCOCUM', NULL, 28, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-292', 'Suavinex SEL PORTADOCOCUMENTOS WONDERLAND RS', 'Suavinex SEL PORTADOCOCUMENTOS WONDERLAND RS', 27.9, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20SEL%20PORTADOCOCUM', NULL, 28, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-293', 'Suavinex SEL BOLSO MAT BANDOLERA WONDERLAND BG', 'Suavinex SEL BOLSO MAT BANDOLERA WONDERLAND BG', 72.9, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20SEL%20BOLSO%20MAT%20BA', NULL, 73, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-294', 'Suavinex SEL BOLSO MAT BANDOLERA WONDERALAN LIB', 'Suavinex SEL BOLSO MAT BANDOLERA WONDERALAN LIB', 72.9, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20SEL%20BOLSO%20MAT%20BA', NULL, 73, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-295', 'Suavinex SEL BOLSO MAT BANDOLERA WONDERLAND GR', 'Suavinex SEL BOLSO MAT BANDOLERA WONDERLAND GR', 72.9, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20SEL%20BOLSO%20MAT%20BA', NULL, 73, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-296', 'Suavinex SEL BOLSO MAT BANDOLERA WONDERLAND RS', 'Suavinex SEL BOLSO MAT BANDOLERA WONDERLAND RS', 72.9, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20SEL%20BOLSO%20MAT%20BA', NULL, 73, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-297', 'Suavinex SEL BOLSO MAT PEQUEÑO WONDERLAND BG', 'Suavinex SEL BOLSO MAT PEQUEÑO WONDERLAND BG', 59.9, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20SEL%20BOLSO%20MAT%20PE', NULL, 60, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-298', 'Suavinex SEL BOLSO MAT PEQUEÑO WONDERLAND LIB', 'Suavinex SEL BOLSO MAT PEQUEÑO WONDERLAND LIB', 59.9, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20SEL%20BOLSO%20MAT%20PE', NULL, 60, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-299', 'Suavinex SEL BOLSO MAT PEQUEÑO WONDERLAND GR', 'Suavinex SEL BOLSO MAT PEQUEÑO WONDERLAND GR', 59.9, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20SEL%20BOLSO%20MAT%20PE', NULL, 60, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-300', 'Suavinex SEL BOLSO MAT PEQUEÑO WONDERLAND RS', 'Suavinex SEL BOLSO MAT PEQUEÑO WONDERLAND RS', 59.9, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20SEL%20BOLSO%20MAT%20PE', NULL, 60, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-301', 'Suavinex SPRAY DE MANOS 100ML', 'Suavinex SPRAY DE MANOS 100ML', 3.75, NULL, 'higiene', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20SPRAY%20DE%20MANOS%201', NULL, 4, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-302', 'S4 COLUTORIO ENCIAS 500ML', 'S4 COLUTORIO ENCIAS 500ML', 10.75, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=S4%20COLUTORIO%20ENCIAS%20500ML', NULL, 11, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-303', 'S4 GEL BIOADHESIVO ENCIAS 30ML', 'S4 GEL BIOADHESIVO ENCIAS 30ML', 7.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=S4%20GEL%20BIOADHESIVO%20ENCIAS', NULL, 8, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-304', 'Suavinex MOSQ PARCHES CITRONELA 36U', 'Suavinex MOSQ PARCHES CITRONELA 36U', 7.15, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20MOSQ%20PARCHES%20CIT', NULL, 7, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-305', 'Suavinex MOSQ ROLL-ON POSTPICADURA 15ML', 'Suavinex MOSQ ROLL-ON POSTPICADURA 15ML', 8.2, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20MOSQ%20ROLL-ON%20POS', NULL, 8, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-306', 'Suavinex SPRAY CITRONELA 100ML ES', 'Suavinex SPRAY CITRONELA 100ML ES', 11.25, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20SPRAY%20CITRONELA%20', NULL, 11, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-307', 'Suavinex MOSQ TATOOS CITRONELA 14U', 'Suavinex MOSQ TATOOS CITRONELA 14U', 4.65, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20MOSQ%20TATOOS%20CITR', NULL, 5, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-308', 'Suavinex MOSQ SPRAY REPELENTE FORTE 100ML', 'Suavinex MOSQ SPRAY REPELENTE FORTE 100ML', 11.25, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20MOSQ%20SPRAY%20REPEL', NULL, 11, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-309', 'Suavinex MOSQ SET ENJOY_GO', 'Suavinex MOSQ SET ENJOY_GO', 13.5, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20MOSQ%20SET%20ENJOY_G', NULL, 14, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-310', 'Suavinex MOSQ LOCION REPELENTE PEDIATRIC 100ML', 'Suavinex MOSQ LOCION REPELENTE PEDIATRIC 100ML', 11.25, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20MOSQ%20LOCION%20REPE', NULL, 11, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-311', 'Suavinex GAFAS DE SOL INFANTILES 0/12M', 'Suavinex GAFAS DE SOL INFANTILES 0/12M', 22.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20GAFAS%20DE%20SOL%20INF', NULL, 23, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-312', 'Suavinex GAFAS DE SOL INFANTILES 12/24M', 'Suavinex GAFAS DE SOL INFANTILES 12/24M', 22.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20GAFAS%20DE%20SOL%20INF', NULL, 23, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-313', 'Suavinex GAFAS DE SOL INFANTILES 24/36M', 'Suavinex GAFAS DE SOL INFANTILES 24/36M', 22.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20GAFAS%20DE%20SOL%20INF', NULL, 23, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-314', 'Suavinex GAFAS DE SOL INFANTILES 3Y-8Y', 'Suavinex GAFAS DE SOL INFANTILES 3Y-8Y', 22.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20GAFAS%20DE%20SOL%20INF', NULL, 23, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-315', 'Suavinex GAFAS DE SOL INFANTILES ADULTO', 'Suavinex GAFAS DE SOL INFANTILES ADULTO', 25.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20GAFAS%20DE%20SOL%20INF', NULL, 26, 10, true, 4.5, 0);;
