-- PARTE 2: 100 productos
DELETE FROM products;
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-101', 'Suavinex ZERO.ZERO BIB ANTICÓLICO 180ML A MED', 'Suavinex ZERO.ZERO BIB ANTICÓLICO 180ML A MED', 14.45, NULL, 'bebe-mama', '', 'Suavinex', 'https://farmaciacid.com/7311-home_default/suavinex-biberon-anticolico-silicona-lactancia-mixta-180-ml-medium.jpg', NULL, 14, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-102', 'Suavinex ZERO.ZERO BIB ANTICÓLICO 180ML S MED', 'Suavinex ZERO.ZERO BIB ANTICÓLICO 180ML S MED', 14.45, NULL, 'bebe-mama', '', 'Suavinex', 'https://farmaciacid.com/7301-home_default/suavinex-biberon-anticolico-silicona-flujo-lento-180-ml-medium.jpg', NULL, 14, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-103', 'Suavinex ZERO.ZERO BIB ANTICÓLICO 180ML A DEEP', 'Suavinex ZERO.ZERO BIB ANTICÓLICO 180ML A DEEP', 14.45, NULL, 'bebe-mama', '', 'Suavinex', 'https://farmaciacid.com/7314-home_default/suavinex-biberon-anticolico-silicona-lactancia-mixta-180-ml-deep.jpg', NULL, 14, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-104', 'Suavinex ZERO.ZERO BIB ANTICÓLICO 180ML S DEEP', 'Suavinex ZERO.ZERO BIB ANTICÓLICO 180ML S DEEP', 14.45, NULL, 'bebe-mama', '', 'Suavinex', 'https://farmaciacid.com/7336-home_default/suavinex-biberon-anticolico-silicona-flujo-lento-180-ml-deep.jpg', NULL, 14, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-105', 'Suavinex ZERO.ZERO BIB ANTICÓLICO 270ML M LIGHT', 'Suavinex ZERO.ZERO BIB ANTICÓLICO 270ML M LIGHT', 16.45, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20ZERO.ZERO%20BIB%20AN', NULL, 16, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-106', 'Suavinex ZERO.ZERO BIB ANTICÓLICO 270ML M MED', 'Suavinex ZERO.ZERO BIB ANTICÓLICO 270ML M MED', 16.45, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20ZERO.ZERO%20BIB%20AN', NULL, 16, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-107', 'Suavinex ZERO.ZERO BIB ANTICÓLICO 270ML M DEEP', 'Suavinex ZERO.ZERO BIB ANTICÓLICO 270ML M DEEP', 16.45, NULL, 'bebe-mama', '', 'Suavinex', 'https://farmaciacid.com/7291-home_default/suavinex-biberon-anticolico-silicona-flujo-medio-270-ml-deep.jpg', NULL, 16, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-108', 'Suavinex ZERO.ZERO TET ANTICÓL SIL A 2U SHADES', 'Suavinex ZERO.ZERO TET ANTICÓL SIL A 2U SHADES', 10.15, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20ZERO.ZERO%20TET%20AN', NULL, 10, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-109', 'Suavinex ZERO.ZERO TET ANTIC SIL S 2U SHADES', 'Suavinex ZERO.ZERO TET ANTIC SIL S 2U SHADES', 10.15, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20ZERO.ZERO%20TET%20AN', NULL, 10, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-110', 'Suavinex ZERO.ZERO TET ANTIC SIL M 2U SHADES', 'Suavinex ZERO.ZERO TET ANTIC SIL M 2U SHADES', 10.15, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20ZERO.ZERO%20TET%20AN', NULL, 10, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-111', 'Suavinex ZERO.ZERO TET ANTIC SIL L 2U SHADES', 'Suavinex ZERO.ZERO TET ANTIC SIL L 2U SHADES', 10.15, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20ZERO.ZERO%20TET%20AN', NULL, 10, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-112', 'Suavinex TETINA FISOLÓGICA SILICONA S 2U', 'Suavinex TETINA FISOLÓGICA SILICONA S 2U', 8.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20TETINA%20FISOL%C3%93GIC', NULL, 9, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-113', 'Suavinex TETINA FISOLÓGICA SILICONA M 2U', 'Suavinex TETINA FISOLÓGICA SILICONA M 2U', 8.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20TETINA%20FISOL%C3%93GIC', NULL, 9, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-114', 'Suavinex TETINA FISOLÓGICA SILICONA L 2U', 'Suavinex TETINA FISOLÓGICA SILICONA L 2U', 8.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20TETINA%20FISOL%C3%93GIC', NULL, 9, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-115', 'Suavinex TETINA FISIOLÓGICA SILICONA XL 2U', 'Suavinex TETINA FISIOLÓGICA SILICONA XL 2U', 8.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://farmaciacid.com/8578-home_default/suavinex-tetina-silicona-fisiologica-flujo-denso-xl-2uds.jpg', NULL, 9, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-116', 'Suavinex ZERO.ZERO TET ANTIC SIL L 2U FAIR', 'Suavinex ZERO.ZERO TET ANTIC SIL L 2U FAIR', 10.15, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20ZERO.ZERO%20TET%20AN', NULL, 10, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-117', 'Suavinex ZERO.ZERO TET ANTIC SIL M 2U FAIR', 'Suavinex ZERO.ZERO TET ANTIC SIL M 2U FAIR', 10.15, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20ZERO.ZERO%20TET%20AN', NULL, 10, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-118', 'Suavinex ZERO.ZERO TET ANTIC SIL S 2U FAIR', 'Suavinex ZERO.ZERO TET ANTIC SIL S 2U FAIR', 10.15, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20ZERO.ZERO%20TET%20AN', NULL, 10, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-119', 'Suavinex ZERO.ZERO TET ANTIC SIL A 2U FAIR', 'Suavinex ZERO.ZERO TET ANTIC SIL A 2U FAIR', 10.15, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20ZERO.ZERO%20TET%20AN', NULL, 10, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-120', 'Suavinex SEL CH WONDER BUTTERFLY FIS SIL 0/6M', 'Suavinex SEL CH WONDER BUTTERFLY FIS SIL 0/6M', 8.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20SEL%20CH%20WONDER%20BU', NULL, 9, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-121', 'Suavinex SEL CH WONDER BUTTERFLY FIS SIL 6/18', 'Suavinex SEL CH WONDER BUTTERFLY FIS SIL 6/18', 8.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://farmaciacid.com/8994-home_default/suavinex-chupete-wonder-butterfly-tetina-fisiologica-6-18-m.jpg', NULL, 9, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-122', 'Suavinex SEL CH SMOOTHIE ANA 0/6M COL ESS SOFT', 'Suavinex SEL CH SMOOTHIE ANA 0/6M COL ESS SOFT', 7.5, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20SEL%20CH%20SMOOTHIE%20', NULL, 8, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-123', 'Suavinex SEL CH SMOOTHIE ANA 6/18M COL ESS SOFT', 'Suavinex SEL CH SMOOTHIE ANA 6/18M COL ESS SOFT', 7.5, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20SEL%20CH%20SMOOTHIE%20', NULL, 8, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-124', 'Suavinex CH NIGHT_DAY FIS SIL 0/6M 2U PRINTS', 'Suavinex CH NIGHT_DAY FIS SIL 0/6M 2U PRINTS', 10.35, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20CH%20NIGHT_DAY%20FIS', NULL, 10, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-125', 'Suavinex CH NIGHT_DAY FIS SIL 6/18M 2U PRINTS', 'Suavinex CH NIGHT_DAY FIS SIL 6/18M 2U PRINTS', 10.35, NULL, 'bebe-mama', '', 'Suavinex', 'https://farmaciacid.com/5438-home_default/suavinex-chupete-noche-tetina-fisiologica-silicona-6-18m-2-unidades.jpg', NULL, 10, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-126', 'Suavinex CH ANATÓMICO SIL 0/6M 2U PRINTS', 'Suavinex CH ANATÓMICO SIL 0/6M 2U PRINTS', 10.3, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20CH%20ANAT%C3%93MICO%20SIL', NULL, 10, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-127', 'Suavinex CH ANATÓMICO SIL +18M 2U PRINTS', 'Suavinex CH ANATÓMICO SIL +18M 2U PRINTS', 10.3, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20CH%20ANAT%C3%93MICO%20SIL', NULL, 10, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-128', 'Suavinex CH ANATÓMICO SIL 6/18M 2U PRINTS', 'Suavinex CH ANATÓMICO SIL 6/18M 2U PRINTS', 10.3, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20CH%20ANAT%C3%93MICO%20SIL', NULL, 10, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-129', 'Suavinex CH SX PRO FIS SIL 0/6M 2U PRINTS', 'Suavinex CH SX PRO FIS SIL 0/6M 2U PRINTS', 10.3, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20CH%20SX%20PRO%20FIS%20SI', NULL, 10, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-130', 'Suavinex CH SX PRO FIS SIL 6/18M 2U PRINTS', 'Suavinex CH SX PRO FIS SIL 6/18M 2U PRINTS', 10.3, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20CH%20SX%20PRO%20FIS%20SI', NULL, 10, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-131', 'Suavinex CH SX PRO FIS SIL +18M 2U PRINTS', 'Suavinex CH SX PRO FIS SIL +18M 2U PRINTS', 10.3, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20CH%20SX%20PRO%20FIS%20SI', NULL, 10, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-132', 'Suavinex SEL CH SMOOTHIE FIS 0/6M COL ESS SOFT', 'Suavinex SEL CH SMOOTHIE FIS 0/6M COL ESS SOFT', 7.5, NULL, 'bebe-mama', '', 'Suavinex', 'https://farmaciacid.com/4596-home_default/suavinex-chupete-todosilicona-tetina-fisiologica-0-6m.jpg', NULL, 8, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-133', 'Suavinex SEL CH SMOOTHIE FIS 6/18M COL ESS SOFT', 'Suavinex SEL CH SMOOTHIE FIS 6/18M COL ESS SOFT', 7.5, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20SEL%20CH%20SMOOTHIE%20', NULL, 8, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-134', 'Suavinex ZERO.ZERO CH NEWBORN FIS.S -2/2M FAIR', 'Suavinex ZERO.ZERO CH NEWBORN FIS.S -2/2M FAIR', 8.9, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20ZERO.ZERO%20CH%20NEW', NULL, 9, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-135', 'Suavinex ZERO.ZERO CH FIS SIL 0/6M FAIR', 'Suavinex ZERO.ZERO CH FIS SIL 0/6M FAIR', 8.9, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20ZERO.ZERO%20CH%20FIS', NULL, 9, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-136', 'Suavinex SEL CH WONDER FIS SIL 0/6M SOFT', 'Suavinex SEL CH WONDER FIS SIL 0/6M SOFT', 8.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://farmaciacid.com/6009-home_default/suavinex-chupete-silicona-fisiologico-wonder-soft-color-6-18-m.jpg', NULL, 9, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-137', 'Suavinex SEL CH WONDER FIS SIL 0/6M INTENSE', 'Suavinex SEL CH WONDER FIS SIL 0/6M INTENSE', 8.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://farmaciacid.com/6008-home_default/suavinex-chupete-silicona-fisiologico-wonder-intense-color-6-18-m.jpg', NULL, 9, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-138', 'Suavinex SEL CH WONDER FIS SIL 6/18M SOFT', 'Suavinex SEL CH WONDER FIS SIL 6/18M SOFT', 8.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://farmaciacid.com/6009-home_default/suavinex-chupete-silicona-fisiologico-wonder-soft-color-6-18-m.jpg', NULL, 9, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-139', 'Suavinex SEL CH WONDER FIS SIL 6/18M INTENSE', 'Suavinex SEL CH WONDER FIS SIL 6/18M INTENSE', 8.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://farmaciacid.com/6008-home_default/suavinex-chupete-silicona-fisiologico-wonder-intense-color-6-18-m.jpg', NULL, 9, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-140', 'Suavinex ZERO.ZERO CH NEWBORN FIS.S -2/2M LIGHT', 'Suavinex ZERO.ZERO CH NEWBORN FIS.S -2/2M LIGHT', 8.9, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20ZERO.ZERO%20CH%20NEW', NULL, 9, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-141', 'Suavinex ZERO.ZERO CH FIS SIL 0/6M LIGHT', 'Suavinex ZERO.ZERO CH FIS SIL 0/6M LIGHT', 8.9, NULL, 'bebe-mama', '', 'Suavinex', 'https://farmaciacid.com/7285-home_default/suavinex-chupete-silicona-fisiologico-zero-zero-0-6-meses-1-ud-light.jpg', NULL, 9, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-142', 'Suavinex ZERO.ZERO CH NEWBORN FIS.S -2/2M MED', 'Suavinex ZERO.ZERO CH NEWBORN FIS.S -2/2M MED', 8.9, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20ZERO.ZERO%20CH%20NEW', NULL, 9, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-143', 'Suavinex ZERO.ZERO CH FIS SIL 0/6M MEDIUM', 'Suavinex ZERO.ZERO CH FIS SIL 0/6M MEDIUM', 8.9, NULL, 'bebe-mama', '', 'Suavinex', 'https://farmaciacid.com/7282-home_default/suavinex-chupete-silicona-fisiologico-zero-zero-0-6-m-1ud-medium.jpg', NULL, 9, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-144', 'Suavinex ZERO.ZERO CH NEWBORN FIS S -2/2M DEEP', 'Suavinex ZERO.ZERO CH NEWBORN FIS S -2/2M DEEP', 8.9, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20ZERO.ZERO%20CH%20NEW', NULL, 9, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-145', 'Suavinex ZERO.ZERO CH FIS SIL 0/6M DEEP', 'Suavinex ZERO.ZERO CH FIS SIL 0/6M DEEP', 8.9, NULL, 'bebe-mama', '', 'Suavinex', 'https://farmaciacid.com/7273-home_default/suavinex-chupete-silicona-fisiologico-zero-zero-0-6-m-1-ud-deep.jpg', NULL, 9, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-146', 'Suavinex SEL CH SMOOTHIE FIS 0/6M COL ESS INTEN', 'Suavinex SEL CH SMOOTHIE FIS 0/6M COL ESS INTEN', 7.5, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20SEL%20CH%20SMOOTHIE%20', NULL, 8, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-147', 'Suavinex SEL CH SMOOTHIE FIS 6/18M COL ESS INTE', 'Suavinex SEL CH SMOOTHIE FIS 6/18M COL ESS INTE', 7.5, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20SEL%20CH%20SMOOTHIE%20', NULL, 8, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-148', 'Suavinex SEL CH SMOOTHIE ANA 0/6M COL ESS INT', 'Suavinex SEL CH SMOOTHIE ANA 0/6M COL ESS INT', 7.5, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20SEL%20CH%20SMOOTHIE%20', NULL, 8, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-149', 'Suavinex SEL CH SMOOTHIE ANA 6/18M COL ESS INT', 'Suavinex SEL CH SMOOTHIE ANA 6/18M COL ESS INT', 7.5, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20SEL%20CH%20SMOOTHIE%20', NULL, 8, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-150', 'Suavinex SEL CH SMOOTHIE BTFLY FIS 0/6M COL ES', 'Suavinex SEL CH SMOOTHIE BTFLY FIS 0/6M COL ES', 7.5, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20SEL%20CH%20SMOOTHIE%20', NULL, 8, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-151', 'Suavinex SEL CH SMOOTHIE BTFLY FIS 6/18M COL ES', 'Suavinex SEL CH SMOOTHIE BTFLY FIS 6/18M COL ES', 7.5, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20SEL%20CH%20SMOOTHIE%20', NULL, 8, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-152', 'Suavinex SEL PORTACHUPETES DUO WONDERLAND', 'Suavinex SEL PORTACHUPETES DUO WONDERLAND', 8.25, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20SEL%20PORTACHUPETE', NULL, 8, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-153', 'Suavinex BROCHE CINTA BUTTON PRINTS', 'Suavinex BROCHE CINTA BUTTON PRINTS', 6.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20BROCHE%20CINTA%20BUT', NULL, 7, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-154', 'Suavinex SEL BROCHE TELA WONDERLAND', 'Suavinex SEL BROCHE TELA WONDERLAND', 13.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20SEL%20BROCHE%20TELA%20', NULL, 14, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-155', 'Suavinex PORTACHUPETES PRINTS', 'Suavinex PORTACHUPETES PRINTS', 6.5, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20PORTACHUPETES%20PR', NULL, 7, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-156', 'Suavinex BROCHE PINZA PRINTS', 'Suavinex BROCHE PINZA PRINTS', 6.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20BROCHE%20PINZA%20PRI', NULL, 7, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-157', 'Suavinex SEL BROCHE BOLITAS SIL COL ESSEN SOFT', 'Suavinex SEL BROCHE BOLITAS SIL COL ESSEN SOFT', 12.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20SEL%20BROCHE%20BOLIT', NULL, 13, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-158', 'Suavinex SEL PORTACHUPETES SIL COLOUR ESSENCE', 'Suavinex SEL PORTACHUPETES SIL COLOUR ESSENCE', 12.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20SEL%20PORTACHUPETE', NULL, 13, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-159', 'Suavinex SEL BROCHE SILICONA WONDER SOFT', 'Suavinex SEL BROCHE SILICONA WONDER SOFT', 12.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://farmaciacid.com/6009-home_default/suavinex-chupete-silicona-fisiologico-wonder-soft-color-6-18-m.jpg', NULL, 13, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-160', 'Suavinex SEL BROCHE SILICONA WONDER INTENSE', 'Suavinex SEL BROCHE SILICONA WONDER INTENSE', 12.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://farmaciacid.com/6000-home_default/suavinex-broche-silicona-wonder-intense-color.jpg', NULL, 13, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-161', 'Suavinex SEL BROCHE BOLITAS SIL COL ESSEN INTEN', 'Suavinex SEL BROCHE BOLITAS SIL COL ESSEN INTEN', 12.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20SEL%20BROCHE%20BOLIT', NULL, 13, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-162', 'Suavinex CEPILLO LIMPIABIBERONES DUO', 'Suavinex CEPILLO LIMPIABIBERONES DUO', 8.1, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20CEPILLO%20LIMPIABI', NULL, 8, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-163', 'Suavinex ESTERILIZADOR CH PORTÁTIL DUCCIO', 'Suavinex ESTERILIZADOR CH PORTÁTIL DUCCIO', 29.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20ESTERILIZADOR%20CH', NULL, 30, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-164', 'Suavinex DETERGENTE BIBERONES Y TETINAS 500ML', 'Suavinex DETERGENTE BIBERONES Y TETINAS 500ML', 6.75, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20DETERGENTE%20BIBER', NULL, 7, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-165', 'Suavinex DETERG BIB Y TET PROMO 550+200ML FREE', 'Suavinex DETERG BIB Y TET PROMO 550+200ML FREE', 7.2, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20DETERG%20BIB%20Y%20TET', NULL, 7, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-166', 'Suavinex EXTRACTOR LECHE MANUAL', 'Suavinex EXTRACTOR LECHE MANUAL', 59.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20EXTRACTOR%20LECHE%20', NULL, 60, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-167', 'Suavinex EXTRACTOR LECHE ELÉCTRICO', 'Suavinex EXTRACTOR LECHE ELÉCTRICO', 111.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20EXTRACTOR%20LECHE%20', NULL, 112, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-168', 'Suavinex BOLSAS ALMACENAJE LECHE MATERNA', 'Suavinex BOLSAS ALMACENAJE LECHE MATERNA', 15.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20BOLSAS%20ALMACENAJ', NULL, 16, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-169', 'Suavinex PEZONERA SILICONA TS 2U', 'Suavinex PEZONERA SILICONA TS 2U', 9.25, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20PEZONERA%20SILICON', NULL, 9, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-170', 'Suavinex CONCHAS PROTECTORAS-RECOLECTORAS', 'Suavinex CONCHAS PROTECTORAS-RECOLECTORAS', 13.75, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20CONCHAS%20PROTECTO', NULL, 14, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-171', 'Suavinex MOTHERING EXTRACTOR MANOS LIBRES', 'Suavinex MOTHERING EXTRACTOR MANOS LIBRES', 189, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20MOTHERING%20EXTRAC', NULL, 189, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-172', 'Suavinex PEZONERA SILICONA TM 2U', 'Suavinex PEZONERA SILICONA TM 2U', 9.3, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20PEZONERA%20SILICON', NULL, 9, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-173', 'Suavinex SACALECHE', 'Suavinex SACALECHE', 9.25, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20SACALECHE', NULL, 9, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-174', 'Suavinex SEL VAJILLA INFANTIL +6M WONDERLAND VD', 'Suavinex SEL VAJILLA INFANTIL +6M WONDERLAND VD', 34.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20SEL%20VAJILLA%20INFA', NULL, 35, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-175', 'Suavinex SEL VAJILLA INFANTIL +6M WONDERLAND RS', 'Suavinex SEL VAJILLA INFANTIL +6M WONDERLAND RS', 34.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20SEL%20VAJILLA%20INFA', NULL, 35, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-176', 'Suavinex SEL CUCHARA SILICONA +4M COLOUR ESSENC', 'Suavinex SEL CUCHARA SILICONA +4M COLOUR ESSENC', 6.45, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20SEL%20CUCHARA%20SILI', NULL, 6, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-177', 'Suavinex DOSIFICADOR DE LECHE EN POLVO', 'Suavinex DOSIFICADOR DE LECHE EN POLVO', 7.85, NULL, 'bebe-mama', '', 'Suavinex', 'https://farmaciacid.com/10304-home_default/suavinex-dosificador-leche-en-polvo.jpg', NULL, 8, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-178', 'Suavinex BABERO SILICONA 2025 I3', 'Suavinex BABERO SILICONA 2025 I3', 12.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20BABERO%20SILICONA%20', NULL, 13, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-179', 'Suavinex SEL TERMO LIQUIDO 500ML WONDERLAND VD', 'Suavinex SEL TERMO LIQUIDO 500ML WONDERLAND VD', 24.75, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20SEL%20TERMO%20LIQUID', NULL, 25, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-180', 'Suavinex SEL TERMO PAPILLERO 400ML WONDERLAN VD', 'Suavinex SEL TERMO PAPILLERO 400ML WONDERLAN VD', 25.25, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20SEL%20TERMO%20PAPILL', NULL, 25, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-181', 'Suavinex SEL TERMO LIQUIDO 500ML WONDERLAND RS', 'Suavinex SEL TERMO LIQUIDO 500ML WONDERLAND RS', 24.75, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20SEL%20TERMO%20LIQUID', NULL, 25, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-182', 'Suavinex SEL TERMO PAPILLER 400ML WONDERLAND RS', 'Suavinex SEL TERMO PAPILLER 400ML WONDERLAND RS', 25.25, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20SEL%20TERMO%20PAPILL', NULL, 25, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-183', 'Suavinex TAZA ENTRENAMIENTO 360 +12M WONDERLAND', 'Suavinex TAZA ENTRENAMIENTO 360 +12M WONDERLAND', 11.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20TAZA%20ENTRENAMIEN', NULL, 12, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-184', 'Suavinex SEL VAJILLA SIL COLOUR ESSENCE SOFT', 'Suavinex SEL VAJILLA SIL COLOUR ESSENCE SOFT', 39.25, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20SEL%20VAJILLA%20SIL%20', NULL, 39, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-185', 'Suavinex SEL VAJILLA SIL COLOUR ESSENCE INTENSE', 'Suavinex SEL VAJILLA SIL COLOUR ESSENCE INTENSE', 39.25, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20SEL%20VAJILLA%20SIL%20', NULL, 39, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-186', 'Suavinex SEL TERMO PAPILLER 400ML WONDERLAN LIB', 'Suavinex SEL TERMO PAPILLER 400ML WONDERLAN LIB', 25.25, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20SEL%20TERMO%20PAPILL', NULL, 25, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-187', 'Suavinex SEL TERMO LIQUIDO 500ML WONDERLAN LIB', 'Suavinex SEL TERMO LIQUIDO 500ML WONDERLAN LIB', 24.75, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20SEL%20TERMO%20LIQUID', NULL, 25, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-188', 'Suavinex SEL TAZA APRENDIZAJE 3 en 1 COL ESSE', 'Suavinex SEL TAZA APRENDIZAJE 3 en 1 COL ESSE', 16.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20SEL%20TAZA%20APRENDI', NULL, 17, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-189', 'Suavinex SEL ALIMENTADOR ANTIAHOGO SIL COL ESS', 'Suavinex SEL ALIMENTADOR ANTIAHOGO SIL COL ESS', 13.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20SEL%20ALIMENTADOR%20', NULL, 14, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-190', 'Suavinex SEL PRECUCHAR APREND SIL 2U COLOU ESS', 'Suavinex SEL PRECUCHAR APREND SIL 2U COLOU ESS', 12.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20SEL%20PRECUCHAR%20AP', NULL, 13, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-191', 'Suavinex SEL PLATO CON DIVISION SIL COL ESS BG', 'Suavinex SEL PLATO CON DIVISION SIL COL ESS BG', 17.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20SEL%20PLATO%20CON%20DI', NULL, 18, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-192', 'Suavinex SEL PLATO CON DIVISION SIL COL ESS VD', 'Suavinex SEL PLATO CON DIVISION SIL COL ESS VD', 17.95, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20SEL%20PLATO%20CON%20DI', NULL, 18, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-193', 'Suavinex SEL CUCHARA INFANTIL +6M 2U WONDERLAND', 'Suavinex SEL CUCHARA INFANTIL +6M 2U WONDERLAND', 4.75, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20SEL%20CUCHARA%20INFA', NULL, 5, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-194', 'Suavinex CEPILLO-PEINE DREAMS RS', 'Suavinex CEPILLO-PEINE DREAMS RS', 9.25, NULL, 'higiene', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20CEPILLO-PEINE%20DR', NULL, 9, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-195', 'Suavinex CEPILLO-PEINE DREAMS AZ', 'Suavinex CEPILLO-PEINE DREAMS AZ', 9.25, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20CEPILLO-PEINE%20DR', NULL, 9, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-196', 'Suavinex CEPILLO-PEINE DREAMS BG', 'Suavinex CEPILLO-PEINE DREAMS BG', 9.25, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20CEPILLO-PEINE%20DR', NULL, 9, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-197', 'Suavinex SET MANICURA BABY CARE ESS DREAMS AZ', 'Suavinex SET MANICURA BABY CARE ESS DREAMS AZ', 29.45, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20SET%20MANICURA%20BAB', NULL, 29, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-198', 'Suavinex SET MANICURA BABY CARE ESS DREAMS RS', 'Suavinex SET MANICURA BABY CARE ESS DREAMS RS', 29.45, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20SET%20MANICURA%20BAB', NULL, 29, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-199', 'Suavinex SET MANICURA BABY CARE ESS TIGERS BG', 'Suavinex SET MANICURA BABY CARE ESS TIGERS BG', 29.45, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20SET%20MANICURA%20BAB', NULL, 29, 10, true, 4.5, 0);
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
('prod-200', 'Suavinex TERMOMETRO BAÑO DREAMS', 'Suavinex TERMOMETRO BAÑO DREAMS', 6.75, NULL, 'bebe-mama', '', 'Suavinex', 'https://via.placeholder.com/400x400/f7f7f7/5D8A82?text=Suavinex%20TERMOMETRO%20BA%C3%91O%20', NULL, 7, 10, true, 4.5, 0);;
